# Generated by Django 3.1.6 on 2021-03-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20210307_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_number', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('observation', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('whatsapp', models.CharField(max_length=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
            options={
                'db_table': 'CLIENT',
            },
        ),
    ]
