# Generated by Django 3.1.6 on 2021-03-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observation',
            field=models.TextField(null=True),
        ),
    ]
