# Generated by Django 3.1.6 on 2021-03-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuit', '0001_initial'),
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.locker'),
        ),
    ]
