# Generated by Django 3.1.6 on 2021-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuit', '0004_auto_20210320_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='type',
            field=models.CharField(choices=[('EXTRAJUDICIAL', 'Extrajudicial'), ('JUDICIAL', 'Judicial')], default='EXTRAJUDICIAL', max_length=13),
        ),
    ]
