# Generated by Django 3.1.12 on 2021-07-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210307_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='social_number',
            new_name='document_number',
        ),
    ]
